### ISSUE TITLE
Help about the "expanded" version

### ISSUE THREAD

**Issue by Yomguithereal** [mattdesl/webgl-lines#3]
Hello @mattdesl. I wanted to thank you for your very insightful [article](http://mattdesl.svbtle.com/drawing-lines-is-hard) and just wanted to ask you some questions. I am trying to apply your "expanded" version to optimize the drawing of a graph (I am currently using triangulated lines and this is causing me some performance issues unrelated with the GPU).

The thing I don't understand, and sorry if this is trivial and I missed it, is the following:

Let's say I want to draw a straight line. This line is composed of two points. With your methods I then need to render four vertices, no? How can the `TRIANGLES` drawing mode solves it since it is supposed to take every three consecutive vertices to produce triangles.

**Comment by mattdesl** [comment]
You need four vertices, one for each point in your line segment. However, you also need to submit the data with indices (aka elements) that tell the gpu how to draw the triangles. This way you can use 4 verts (imagine an indexed quad) rather than 6 verts, since two of the vertices can use the same element index. 😁

**Comment by Yomguithereal** [comment]
Oh. So it's the indices. Thanks a lot @mattdesl!
